---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudlab-apps
  labels:
    name: cloudlab-apps
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudlab-monitoring
  labels:
    name: cloudlab-monitoring
    environment: production
